name: auto push
on:
  push:
  schedule:
  # update every week, in case base image is updated
  - cron:  '0 0 * * 0'
jobs:
  auto-push:
    name: auto push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
        run: |
          echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$OWNER" --password-stdin
          docker build -t "ghcr.io/$OWNER/openvpn:latest" .
          docker push "ghcr.io/$OWNER/openvpn:latest"
